# Generated by Django 3.2.6 on 2023-09-29 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('anotacionjesimportantes', models.CharField(max_length=500)),
                ('eps', models.CharField(max_length=20)),
                ('rh', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('pacienteasociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.paciente')),
            ],
        ),
    ]
