# Generated by Django 3.2.6 on 2023-09-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cedula', models.IntegerField(default=None)),
                ('edad', models.IntegerField(default=None)),
                ('fechaNacimiento', models.DateField(default=None)),
            ],
        ),
    ]
